---
- name: Ensure directory exists
  file:
    path: "{{ docker_compose_file_dir }}"
    state: directory
    mode: "0755"

- name: Template docker-compose file
  template:
    src: templates/docker-compose-app.yml.j2
    dest: "{{ docker_compose_file_dir }}/docker-compose.yml"
    mode: "0700"
    force: yes

- name: Template petclinic.env file
  template:
    src: templates/petclinic.env.j2
    dest: "{{ docker_compose_file_dir }}/petclinic.env"
    mode: "0700"
    force: yes

- name: Run docker-compose.yml file
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_file_dir }}"
  register: output

- name: Show results
  debug:
    var: output
