---
- name: Ensure directory exists
  file:
    path: "{{ docker_compose_file_dir }}"
    state: directory
    mode: "0755"

- name: Template docker-compose file
  template:
    src: templates/docker-compose-db-standby.yml.j2
    dest: "{{ docker_compose_file_dir }}/docker-compose.yml"
    mode: "0700"
    force: yes

- name: Template postgres.env file
  template:
    src: templates/postgres.env.j2
    dest: "{{ docker_compose_file_dir }}/postgres.env"
    mode: "0700"
    force: yes

- name: Ensure shared directory exists
  file:
    path: "{{ docker_compose_file_dir }}/shared"
    state: directory
    mode: "0755"

- name: Template standby-entrypoint.sh file
  template:
    src: templates/standby-entrypoint.sh.j2
    dest: "{{ docker_compose_file_dir }}/shared/standby-entrypoint.sh"
    mode: "0755"
    force: yes

- name: Run docker-compose.yml file
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_file_dir }}"
  register: output

- name: Show results
  debug:
    var: output
