services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    ports:
      - 8050:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker/
    restart: always

  promtail:
    image: grafana/promtail:3.2.2
    volumes:
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail.yml:/etc/promtail/promtail.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: always
    command:
      - -config.file=/etc/promtail/promtail.yaml

  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    ports:
      - "9100:9100"
    restart: always
    command:
      - "--path.rootfs=/host"
    volumes:
      - /:/host:ro,rslave
