services:
  petclinic:
    image: ${IMAGE}:${TAG}
    ports:
      - 80:8080
    environment:
      - POSTGRES_PASS=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
      - POSTGRES_URL=jdbc:postgresql://${DB_ADDRESS}:5432/petclinic
      - SPRING_PROFILES_ACTIVE=postgres
    restart: always
