name: Terraform plan on pull request

on:
  pull_request: # Trigger plan on pull requests
    branches:
      - "**" # From any branch

env:
  PROJECT_ID: "petclinic-444616"
  SERVICE_ACCOUNT: "github-actions-petclinic-tf@petclinic-444616.iam.gserviceaccount.com"
  WORKLOAD_IDENTITY_PROVIDER: "projects/334892833978/locations/global/workloadIdentityPools/github-actions/providers/github-provider-terraform-plan"

jobs:
  terraform_plan:
    permissions:
      contents: "write"
      id-token: "write"
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gcp
    steps:
      - uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          project_id: ${{ env.PROJECT_ID }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      - name: Initialize
        run: terraform init
      - name: Plan
        run: terraform plan --lock=false -out terraform.plan
      - run: terraform show -json terraform.plan > terraform.json
      - run: terraform show -no-color terraform.plan > terraform.text

      - uses: ahmadnassri/action-terraform-report@v4
        with:
          terraform-json: ${{ github.workspace }}/gcp/terraform.json
          terraform-text: ${{ github.workspace }}/gcp/terraform.text
          remove-stale-reports: true
